name: Publish Docker image

on:
  push:
    branches:
      [master]

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $username -p $password
      - name: Build and push Docker image for Front-end
        run: |
          docker build -t $username/final-project-decider-front-end
          docker run -ti --rm $username/final-project-decider-front-end
          working-directory: front-end
      - name: Build and push Docker image for Back-end
        run: |
          docker build -t $username/final-project-decider-back-end
          docker run -ti --rm $username/final-project-decider-back-end
          working-directory: back-end
        
          

